# Faça um programa que leia um número inteiro qualquer e mostre na tela a sua tabuada
print('Olá eu sou o TABUADINHA!')
num = int(input('Digite um número: '))
print('-' * 20)
print(f'TABUADA DO Nº {num}'.center(20))
print('-' * 20)
print(f' 1 * {num} = {1 * num}'.center(20))
print(f' 2 * {num} = {2 * num}'.center(20))
print(f' 3 * {num} = {3 * num}'.center(20))
print(f' 4 * {num} = {4 * num}'.center(20))
print(f' 5 * {num} = {5 * num}'.center(20))
print(f' 6 * {num} = {6 * num}'.center(20))
print(f' 7 * {num} = {7 * num}'.center(20))
print(f' 8 * {num} = {8 * num}'.center(20))
print(f' 9 * {num} = {9 * num}'.center(20))
print('-' * 20)
